print("harpoon loaded")
local mark = require("harpoon.mark")
local ui = require("harpoon.ui")

vim.keymap.set("n", "<leader>a", mark.add_file)
vim.keymap.set("n", "<leader>ho", ui.toggle_quick_menu)
vim.keymap.set("n", "<leader>w", function() ui.nav_file(1) end)
vim.keymap.set("n", "<leader>o", function() ui.nav_file(2) end)
vim.keymap.set("n", "<leader>v", function() ui.nav_file(3) end)
vim.keymap.set("n", "<leader>n", function() ui.nav_file(4) end)
vim.keymap.set("n", "<M-n>", function() ui.nav_next() end)
vim.keymap.set("n", "<M-p>", function() ui.nav_prev() end)
