[helpers]

[default]
depends = []

[nvim.files]
nvim = "~/.config/nvim"

[tmux.files]
tmux = "~/.tmux.conf"

[zsh.files]
zshrc = "~/.zshrc"

[gitconfig.files]
gitconfig = "~/.gitconfig"

[gitconfig.variables]
username = "bker"

[alacritty.files]
alacritty = "~/.alacritty.toml"

[hyperland.files]
hyprland = "~/.config/hypr/"

[waybar.files]
waybar = "~/.config/waybar/"
